### ISSUE TITLE
Webpack babel problems

### ISSUE THREAD

**Issue by brettz9** [jdlehman/sourcemap-transformer#1]
Hi,

When cloning your repository (which looks to be very useful, btw!), I'm trying to find out where something is failing for me inside of your code. However, in order to avoid the uglification in the build step, when I run `npm run build` (after `npm install`) (even before modifying your existing file), I get an "unexpected token" error. It seems it is not recognizing ES6 modules. Adding `query: {presets: ['es2015']}` to the module loader object did not help. Might you have a chance to take a look?

**Comment by brettz9** [comment]
Apologies, had been working out of the wrong directory!

**Comment by jdlehman** [comment]
Yep, it works for me, but I think that is the error you will get with the wrong version of webpack (at least that is how I was able to reproduce it). I'll update the dependencies soon to help avoid people from hitting similar problems

**Comment by brettz9** [comment]
Thanks... Btw, I didn't include `dist` updates on my latter PRs in case you might wish to tweak, so, especially after #4 (or if you wish, as part of #4), we should probably get those (now two) files updates.
